services:
  db:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ${pg_password}
    ports:
      - "5432:${pg_port}"
    networks:
      - postgres
networks:
  postgres:
volumes:
  postgresql_data: